creation_rules:
  - path_regex: apps/.*\.sops\.yaml$
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - age:
          - age19k05sfsffws7qejd4d0r0qd3xg0em5tqs8p85e3vq9kxy2dz2sssezvj83
          - age1cm29zxftpl6m77k4pau9et3kvpy7uj2kna5ls5jywnq67c8kd4qq3cxwa8
