apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-conf
data:
  default.conf: |
    server {
      listen 8080;
      location = /healthz { return 200 "ok\n"; }
      location / { root /usr/share/nginx/html; }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook-html
data:
  index.html: |
    <h1>Alice's guestbook v1</h1>
