apiVersion: v1
kind: Secret
metadata:
    name: ana-phoenix
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:o4kKhr6ep+nIoaeupXnZr9w2NExVmdfweIR4cVE/amo=,iv:bAaTUXW5pxxF0zez0ShcgVuaKrWNBieUqRL9LoQ78pA=,tag:X9VFmkxq6fqM288JilSV/g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:bjqs+ubMKLcL8rJTkGF0v5hBN6jtsf9bu++KvhdWhZd9FusXSB14wdeV32A2KkqrQ+cOeW780Js4X5jNI2edSQ==,iv:wkNSlC4R1ADIplHfoCzNKhk2nekCwm2rUiIuoLSFayQ=,tag:lkapPjSjFa1r5j39ogQK/g==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:uRVw5dsRxZ7X5oz5Gdz5cfbsfN3KBN9+t7DerY9t1d+AXkCRsFHF2CGUoAVcfWInQlSTO+yM+Ryd7XlhL2sERw==,iv:Vwj5Mrz/6sX2oD6lsVaMOpm4rZt0cWvIdDuRRjZ1vW0=,tag:olJ3r3UgNnn5ehHMfKlmlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK3h6K2YxT3FqczFhd1ZZ
            dm5KOEdwSlQ2ZnpYUmtuUkVIMmFVZHVGakNvCjVJQnhYMVRvQnY3MXVzZHluWjlx
            QzRxenhUbmEvVGVoZGVoSHNUaEdFTmcKLS0tIEdEWnRFWUc4aGNsVFJxdFphbGJT
            VERIbGkxU20zSXV4WUJLZ3FlL1M1OHMKupSQoyOUWm0CW3TqWNnlRYBUpc7odQJw
            uu6qacpZU+zc4cQaZXYR9eGHk3ugbEHOiaAm4FwzHSXVWAljNPFZjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19k05sfsffws7qejd4d0r0qd3xg0em5tqs8p85e3vq9kxy2dz2sssezvj83
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMS0ZPQ2F2eXAzdWhyRFA1
            bUxKOVlqWTFGcUQyZUw0ODBmNlIrUXE4a0J3CmRkZ2NGUWlDWTd1UktUaFhFS0dm
            UlU1NEtlMk5sRi9jS0lvcmhWSHErY2sKLS0tIC8vSkYyRnU3d1EwcGM4c3Q0S3Fz
            MXNJUW9wdElmWEF4dnZDaG4ybktNeFEKcgoUaAWCyLHygoigqtvCYHA7JmSImOwe
            mgHYpjHo6SPq4dH6QsCkGjNl85ENEMiZOM/JLtYBP0BPxjFxi6/EbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cm29zxftpl6m77k4pau9et3kvpy7uj2kna5ls5jywnq67c8kd4qq3cxwa8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T15:23:17Z"
    mac: ENC[AES256_GCM,data:5nJYbqtIwLlQEdp8y76HkVGfU60hc4Io5t9FFmDWNHGO0dRmVeuDrJCV30EUPev9tZ7zuTOGKb05ZHRbisLROyk6EdGop0AisuLssq43Z2q9TPkKq4G7sbHgfdSYYkrrLhDknL4GGuyLxynysvBfEBcJaTV+tYpmb7iVWxsBVGY=,iv:SyMzoWEy6i992feldKsJ4+m5DhSQkMwu5i9HjaXYYQY=,tag:tfQhpsi4dDhjX/ccoLNDAw==,type:str]
    version: 3.13.3
