apiVersion: v1
kind: Secret
metadata:
    name: notes-auth
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:V4II+0iG8zH6poTslIiIejbx80cm/5MAqZU1OnhIv5F/5UKfZwAURo9SYg==,iv:z85pm0d7w9KfjiJvp550hlJagaTKRWiPbRCdR86WA5k=,tag:GzLnCy/Kg8nh+SxVzA8xhw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTEJveHBnL2oxaFhIaEhU
            TDNJVkgrSlNEa0xKd3RETFpmSVFKQlBUTjFrCk5qL3orODNPN1RDaWp1bVMxc09P
            dmFEbXAvc0hyMmVGQ1kyM3JTUGdmT0UKLS0tIDhRb1VwQUU5SjByUGYxZTlFcU9Y
            ZjZ4SzBCdlA3d1RTWGtaN3dJQm9qbUUKapNYbp8FB53ZjRvf2y1DKkAVotprVUA0
            8WmLem9UuaKuwW03zRT+LpsJdVd1y2ODyTZaOWR6+OymKvoh3TZ7TA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19k05sfsffws7qejd4d0r0qd3xg0em5tqs8p85e3vq9kxy2dz2sssezvj83
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWVhtZExxT1c4dUEyNUt3
            V3JqUGY2RzEzV0NaOGNSbmJER2ZmM0lSTWxzCjhhQUtERStYZ0dWMWs2QW4veklR
            VWIxV2hZOFFGNU5RMzdsM3JpSVZ5SFEKLS0tIFRLL2JqeTZuR0NmVGNrVm1LZlNP
            eDd4SmZLTVd4ZzM5Z2s4ODdzZFcvY1kKuTLDRhiv19mZ5v7oOeAqvwDAsxtzaF+r
            C55zRkNWmhSfg053WDfENEwgbDz9jOezWS0HDuNwF63cH5uEeXoDZA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gphj5sl0r86yyy2q3pumup4p400g40ks9l68lvdvza828gv3598qvmjr73
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T13:19:45Z"
    mac: ENC[AES256_GCM,data:gFR8H2ZgKwiEqSaTI2iJeIVOGM/TR4KZ6frzgD5ofyKUEaGqSQtOBGLEz6W8z3378Y5K46rBJSy5YXyGv0M+a5HNSJDwvpBiJ3TblqfadgnbjMS7L/A0euZZfPHEJpnIhvwkvJtUjjCTlNsswV791hn2EKU4yuZ97mMA+AWccR4=,iv:dh3VWFa9/K9OChuvYyfKhax05xYFm4qxZnaFE7isLHA=,tag:iy3gv9qXTeXfuCjEEAx/dQ==,type:str]
    version: 3.13.3
