apiVersion: v1
kind: Secret
metadata:
    name: notes-auth
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:bzGeK9aKgqorMkjBJgGruc6y/NGYT/NLTKb5fWqpqFwZpsgLkCYQQPpdhg==,iv:FwPhIAdJvs15Z3Ee+aUk3MIDez95FBEGB2vDnNs6yoQ=,tag:7BgvKT51kHMZkcKOuyfFow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSS9JMldUYTE5cWZSVU5o
            STV0N2lTVnFjT2RUckxPRUszTXgyMnhVVlRNCjBoSHp5d1ZJcE9lV2VMQjRzS2Fy
            WXFKbEZCdityTXNybHRXRjVVMEdVKzgKLS0tIFZyY0dFRDNRbTNUOElDVHZTMVh4
            MVdJQWpmNnpGdkFwSVBESVp6MjJuREkKH/uYy/Lch79vt7aDTKmLaZqgCNo0m6oN
            AZEaVJl/2sbwTlm2gXw79FXBBp7Y1M7XzXF5V0ZlnB0MKP624CLK0Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19k05sfsffws7qejd4d0r0qd3xg0em5tqs8p85e3vq9kxy2dz2sssezvj83
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1c1JERDFBSkQrME8vUUhC
            VjRQS0RNdEhOVmpDcis1TUU0bEpVUWlWeWgwCmlQVVgvQ0JtZnI2eUU4Y1psa0FE
            OFZTL2trVGRJaWZJK2JWMXhkcy9UUVEKLS0tIGR2anE5aXZKYkFkLzFJaDVhYWY0
            aVhrZStBTDFNbWdDQmFUQ2hmdVR4UUEKfsK+PlQ9ixOloNlO0FxF+T4phoyRkfOJ
            vzW0yjzuUhQEVZ6CNHHV6cdogUl6rSt1BTSjxcl6TkN+Vuz/l8G8iw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gphj5sl0r86yyy2q3pumup4p400g40ks9l68lvdvza828gv3598qvmjr73
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T13:11:50Z"
    mac: ENC[AES256_GCM,data:gljJM0QF+L0MywZ4SwJOz08m8a7iuoSz9qkEAnbcNCgYAlbseNETIE1HGzJr5kL0OuIGuaT8lbvyrPan0jpxd0L6RRb/+97ImzZgvgmr9LzRKku0HHVlwoKH4SZb9REZsWIDn52WLoY4aWJXzAjTIhTmOuR4XcPKpI8WTYVDTpg=,iv:bUNo33HNUnhahid3cjj8YD9MDnSmN6sPO3eA4yNwEug=,tag:q+a3iQxdyuiwjoojmq74OA==,type:str]
    version: 3.13.3
