apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop
spec:
  replicas: two
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - name: shop
          image: traefik/whoami:v1.12.0
