apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 10m
  chart:
    spec:
      chart: podinfo
      version: 6.15.0
      sourceRef:
        kind: HelmRepository
        name: podinfo
  values:
    replicaCount: 2

    ui:
      message: Scaled down by Eve

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi

    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: selfsigned
      hosts:
        - host: podinfo.192.168.105.200.nip.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: podinfo-tls
          hosts:
            - podinfo.192.168.105.200.nip.io
