replicaCount: 3

ui:
  message: Deployed from github.com/mikaelhug/kubit-apps

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 128Mi

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
  hosts:
    - host: podinfo.192.168.105.200.nip.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: podinfo-tls
      hosts:
        - podinfo.192.168.105.200.nip.io
