apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ben-clock

resources:
  - ns.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: clock-code
    files:
      - main.ts
