apiVersion: v1
kind: Secret
metadata:
    name: cara-queue
type: Opaque
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:aebeZd6MTbrUC2Gvn5PqyFA0sVd7S5DlIWnNnw3Ezg5Srbp8/xmnMA==,iv:pBzgZHtungpmynbD87Pyr//phhfSsRjZ0XKp3Ru9SwI=,tag:U7oSmz5kNzSQOI5wELdwDw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUWN5d2VsK1RsOHJlSktt
            YW1xZjRETVB0blJUSk95NDNZMzRzcHFDemlrCm84a24walVnbXZvcCs5YndHUmI3
            TGEzNmtxQ3FqZnhyNUZSQmUrOXB4blEKLS0tIHBPaDFKSTdBazVpNXVJMjhkQjdY
            VmtWTkEwVVR1M1djWmVyZFg0SDFaaEEKUPGxUPFGVE9j8szwD3gYxNS9LOWxsrJr
            sNDZRSAT/w4elLy/iD5uwdBjKneePTk3BDDvU63V4NmFdybZ7GfzMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19k05sfsffws7qejd4d0r0qd3xg0em5tqs8p85e3vq9kxy2dz2sssezvj83
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMlVITitoUHFBeGFuaFpY
            SjliQzV1TnFFZjdpekZMbW9SRGhUZ0pPRmlZCnEyMk5wTTlpUWg5YXduMGZCWlpM
            Qm5yV3RBNTdHaTRId0RSb3pwVkdnLzAKLS0tIFNoMk9iUDFsT1hUSWQ3ZUV6RXJw
            TTI0UmtjZmtRZ1k5bnZyUVBBUGw0QzgK6D1LZJBp925j5ZGNG7Ldzxb4gKy2uWcq
            z+L2BEHNVLHI4cZMs0psgLnt+1YSHb2gQDSkL+dSH/4PLzLd7rO8KA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cm29zxftpl6m77k4pau9et3kvpy7uj2kna5ls5jywnq67c8kd4qq3cxwa8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T15:23:17Z"
    mac: ENC[AES256_GCM,data:Bv1FxidH1nPyaf818xX5axDXCyFXrCBNQKjGZBY/yihjVpCPTC56fdZqOcGnUHEdJ+BI8uMUBXFSR1EwtrOkNConc/JjOwnDS3Ic8IBzni6D2ykhSlg5oqQu7RuZejYY06XGYtLW8sgHVjdRay506RL58xzrzdhf46mi1CYY3RQ=,iv:KkyUroCD4s5RCMA+by973yOyNUroCOqrEh65o+kcJ+k=,tag:UZaWmSBNjMnX97Kd9mPxHQ==,type:str]
    version: 3.13.3
