apiVersion: v1
kind: Secret
metadata:
    name: eve-bot
type: Opaque
stringData:
    BOT_TOKEN: ENC[AES256_GCM,data:HeaaAA5CWmp5h2oId9xU+Zik398rdCV1lJI5XV44z2W9UydJ,iv:IEJtkBUpKLX2kwv8fGY4MpxyNCmcUyzJ5493nxLirSg=,tag:S5T0Mao3FvlT5FC/YfUiQA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVHdNWDhod1FZNDdmOXFv
            TzJGUlN6Ylo0T2xqNnQzcWI3VW5WYmRPQUFnCjlYb0liTHI2TllobVZtRS9UNHls
            S05ORU9JNnJCL1BlMFlvdFpmVVpZNE0KLS0tIHdTVEl6UVBtZXBOR25TQVVjZFJR
            aS9IQm1IcFVHaHpKNXZvNGhGL3NFZGsKc8/yekiJtovKFbZ5QG5HuO4B0P1g0X5V
            1tdM3l5r/1uouwUuhj8DQ8JSpbcHru8nQL9iAdpwExUMIUa94ay9TQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age19k05sfsffws7qejd4d0r0qd3xg0em5tqs8p85e3vq9kxy2dz2sssezvj83
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSDV4cVhlNmhTd1VMTXZG
            OWphVnh5dGk3RHVCVjlGM3k4Mm1pekpQN0hZCkZBejlZVEJZQnFDMlVLL1J3S0E0
            blk2V0cxaUQrWkEyaU9zVWYxT21IUk0KLS0tIEhxK2VGUkdzYW9yNVRqNTNITzJH
            ZVJNSG5HcVp0WGJNU1hnUjB0MWdNeWcK6wJ0cOPK15ytqzSdC7FkMuj7nxpaA0aY
            3i2vDFohvtXP9Y1otdxMXhZdXM97rl6V92ZHoXSE4Q3zA076R65bKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1cm29zxftpl6m77k4pau9et3kvpy7uj2kna5ls5jywnq67c8kd4qq3cxwa8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T15:18:52Z"
    mac: ENC[AES256_GCM,data:q3zYEkCmnTuoue8431sbClN4w74EpQxAXMI6Yem0gFHU5Kj6MySjJS3+9A0k38SYuq1eFBbECAua+VqeYvv3AE9chmfzXRsEijEk/mjV/hffmB31wLPsCV2zi0H+AFkr2JwywZWsMOiUOxLGqH2FUSHPyMfQQEM2/rdo4+VSsy8=,iv:lFZP6GH3XKEtu0qVmrOkEilbZIIaG5ECTp9pHeq6heA=,tag:r6YneEkvMMUp9MsIgQjdng==,type:str]
    version: 3.13.3
